name: Build PlatformIO Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio
          platformio platform install espressif32
        
      # CD into the directory where the platformio.ini file is located 
      - name: Build Firmware
        run: |
          cd PlatformIO_Generator
          platformio run -e esp32dev
