name: Build Zephyr Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Zephyr Project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: Zephyr_Generator  # Path to your Zephyr project
          toolchains: all   # Specify the toolchain you need

      - name: Build Firmware
        run: |
          west build -p always -b esp32_devkitc_wroom Zephyr_Generator  # Adjust board as needed

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zephyr-build-artifacts
          path: Zephyr_Generator/build/zephyr/*.elf  # Adjust paths as needed for your output files